# Generated by Django 5.2.4 on 2025-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
    ]
