# Generated by Django 5.2.4 on 2025-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=50)),
                ('measurement_type', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=1)),
                ('machine', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
            options={
                'db_table': 'sensores',
            },
        ),
    ]
