# Generated by Django 5.2.4 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('occurrence_number', models.IntegerField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ocorrencias',
            },
        ),
    ]
