# Generated by Django 5.2.4 on 2025-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occurrences', '0001_initial'),
        ('sensor_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='sensor_reading',
            field=models.ForeignKey(db_column='id_leitura', on_delete=django.db.models.deletion.CASCADE, to='sensor_readings.sensorreading'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('id', 'sensor_reading')},
        ),
    ]
