# Generated by Django 5.2.4 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('value_type', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'leitura_sensores',
            },
        ),
    ]
