# Generated by Django 5.2.4 on 2025-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor_readings', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(db_column='id_sensor', on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorreading',
            unique_together={('reading_id', 'sensor')},
        ),
    ]
