# Generated by Django 5.2.4 on 2025-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_date', models.DateField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'empresas_cliente',
            },
        ),
    ]
